apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperclip

resources:
  - namespace.yaml
  - serviceaccount-rbac.yaml
  - sealed-secrets.yaml
  - postgres.yaml
  - paperclip-app.yaml
  - ingress.yaml
  - networkpolicy.yaml
